# Generated by Django 5.0.1 on 2024-01-08 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
