# Generated by Django 5.0.1 on 2024-01-08 17:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_dashboard_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='data',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
