# Generated by Django 5.0.1 on 2024-01-08 17:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_dashboard_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='data',
            field=models.DateTimeField(default=datetime.datetime.utcnow, null=True),
        ),
    ]
