# Generated by Django 5.0.1 on 2024-01-08 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_dashboard_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 8, 13, 51, 45, 960518), null=True),
        ),
    ]
