# Generated by Django 5.0.1 on 2024-01-08 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_alter_dashboard_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='corrente',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='corrente_f1',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='corrente_f2',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='data',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='fP_fase1',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='fP_fase2',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='fP_fase3',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='fp_circuito',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='frequencia',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='potencia_aparente',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='potencia_aparente_f1',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='potencia_aparente_f2',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='potencia_aparente_f3',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='potencia_ativa',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='potencia_ativa_f1',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='potencia_ativa_f2',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='potencia_ativa_f3',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='potencia_reativa',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='potencia_reativa_f1',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='potencia_reativa_f2',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='potencia_reativa_f3',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='tensao',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='tensao_f1',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='tensao_f2',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='tensao_f3',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='balanca',
            field=models.TextField(null=True),
        ),
    ]
