# Generated by Django 5.0.1 on 2024-01-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_remove_dashboard_corrente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='balanca',
            field=models.JSONField(null=True),
        ),
    ]
